/******************************************************************************/
/***       Generated by IBExpert 2012.02.21 23/03/2013 12:28:05 p.m.        ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;

CREATE DATABASE 'D:\Sistemas\Medicos\Data\DATA.FDB'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET NONE;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_CURSO_ID;
SET GENERATOR GEN_CURSO_ID TO 7;

CREATE GENERATOR GEN_CURSO_INSCRIPCION_ID;
SET GENERATOR GEN_CURSO_INSCRIPCION_ID TO 688;

CREATE GENERATOR GEN_CURSO_MODULOS_ID;
SET GENERATOR GEN_CURSO_MODULOS_ID TO 82;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE CURSO (
    IDCURSO         INTEGER NOT NULL,
    DESCRIPCION     VARCHAR(50),
    PRESENCIAL      VARCHAR(2),
    CANTIDAD_HORAS  NUMERIC(5,2),
    MONTO_TOTAL     NUMERIC(5,2),
    OBSERVACION     VARCHAR(100),
    ID_TIPO_CURSO   INTEGER,
    CANTIDAD        INTEGER,
    FECHA_INICIO    DATE,
    FECHA_FIN       DATE
);

CREATE TABLE CURSO_INSCRIPCION (
    IDINSCRIPCION  INTEGER NOT NULL,
    ID_PROVEEDOR   INTEGER,
    IDCURSO        INTEGER,
    FECHA          DATE,
    HORA           TIME,
    IDUSUARIO      INTEGER,
    MONTO_TOTAL    NUMERIC(5,2),
    TERMINADO      VARCHAR(2),
    DESCUENTO      NUMERIC(5,2),
    PAGADO_TOTAL   VARCHAR(2),
    CUOTAS         INTEGER,
    MONTO_CUOTA    NUMERIC(5,2),
    OBSERVACION    VARCHAR(100)
);

CREATE TABLE CURSO_INSCRIPCION_DETALLE (
    IDINSCRIPCION      INTEGER NOT NULL,
    IDCURSO            INTEGER NOT NULL,
    ID_MODULO          INTEGER NOT NULL,
    FECHA_INSCRIPCION  DATE,
    PRESENTE           VARCHAR(2),
    NOTA               NUMERIC(5,2),
    MONTO              NUMERIC(5,2),
    PAGADO             VARCHAR(2),
    FECHA_PAGO         DATE,
    HORA_PAGO          TIME,
    USUARIO_PAGO       INTEGER,
    IDSUBCUENTA        INTEGER,
    DESCUENTO          NUMERIC(5,2),
    SUCURSAL           INTEGER,
    IDRECIBO           INTEGER
);

CREATE TABLE CURSO_MODULOS (
    ID_MODULO       INTEGER NOT NULL,
    IDCURSO         INTEGER NOT NULL,
    DESCRIPCION     VARCHAR(50),
    NUMERO_MODULO   INTEGER,
    CANTIDAD_HORAS  INTEGER,
    EXAMEN          VARCHAR(2),
    MONTO           NUMERIC(5,2),
    FECHA_INICIO    DATE,
    FECHA_FIN       DATE,
    HORA_INICIO     TIME,
    HORA_FIN        TIME,
    OBSERVACION     VARCHAR(255)
);



/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE CURSO ADD CONSTRAINT PK_CURSO PRIMARY KEY (IDCURSO);
ALTER TABLE CURSO_INSCRIPCION ADD CONSTRAINT PK_CURSO_INSCRIPCION PRIMARY KEY (IDINSCRIPCION);
ALTER TABLE CURSO_INSCRIPCION_DETALLE ADD CONSTRAINT PK_CURSO_INSCRIPCION_DETALLE PRIMARY KEY (IDINSCRIPCION, IDCURSO, ID_MODULO);
ALTER TABLE CURSO_MODULOS ADD CONSTRAINT PK_CURSO_MODULOS PRIMARY KEY (ID_MODULO);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE CURSO ADD CONSTRAINT FK_CURSO_TIPO_CURSO FOREIGN KEY (ID_TIPO_CURSO) REFERENCES TIPO_CURSO (ID_TIPO_CURSO);
ALTER TABLE CURSO_INSCRIPCION ADD CONSTRAINT FK_CURSO_INSCRIPCION_CURSO FOREIGN KEY (IDCURSO) REFERENCES CURSO (IDCURSO);
ALTER TABLE CURSO_INSCRIPCION ADD CONSTRAINT FK_CURSO_INSCRIPCION_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES (IDPROVEEDOR);
ALTER TABLE CURSO_INSCRIPCION ADD CONSTRAINT FK_CURSO_INSCRIPCION_USUARIO FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO);
ALTER TABLE CURSO_INSCRIPCION_DETALLE ADD CONSTRAINT FK_CURSO_INSCRIPCION_DETALLE_IN FOREIGN KEY (IDINSCRIPCION) REFERENCES CURSO_INSCRIPCION (IDINSCRIPCION);
ALTER TABLE CURSO_MODULOS ADD CONSTRAINT FK_CURSO_MODULOS_CURSO FOREIGN KEY (IDCURSO) REFERENCES CURSO (IDCURSO);


/******************************************************************************/
/***                                Indices                                 ***/
/******************************************************************************/

CREATE INDEX IDX_CURSO_DESCRIPCION ON CURSO (DESCRIPCION);
CREATE INDEX IDX_CURSO_INSCRIPCION_FECHA ON CURSO_INSCRIPCION (FECHA);
CREATE UNIQUE INDEX IDX_CURSO_INSCRIPCION_UNIQUE ON CURSO_INSCRIPCION (ID_PROVEEDOR, IDCURSO);
CREATE INDEX IDX_CURSO_DETALLE_CURSO ON CURSO_INSCRIPCION_DETALLE (IDCURSO);
CREATE INDEX IDX_CURSO_DETALLE_MODULO ON CURSO_INSCRIPCION_DETALLE (ID_MODULO);
CREATE INDEX IDX_CURSO_DETALLE_PAGADO ON CURSO_INSCRIPCION_DETALLE (PAGADO);
CREATE INDEX IDX_CURSO_DETALLE_SUBCTA ON CURSO_INSCRIPCION_DETALLE (IDSUBCUENTA);
CREATE INDEX CURSO_MODULOS_DESCRIPCION ON CURSO_MODULOS (DESCRIPCION);
CREATE INDEX IDX_CONTROL ON CURSO_MODULOS (ID_MODULO, IDCURSO);
CREATE INDEX IDX_MODULO_NUMERO ON CURSO_MODULOS (NUMERO_MODULO);
CREATE UNIQUE INDEX IDX_MODULO_UNIQUE ON CURSO_MODULOS (IDCURSO, NUMERO_MODULO);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: CURSO_BI */
CREATE TRIGGER CURSO_BI FOR CURSO
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.IDCURSO IS NULL) THEN
    NEW.IDCURSO = GEN_ID(GEN_CURSO_ID,1);
END
^

/* Trigger: CURSO_MODULOS_BI */
CREATE TRIGGER CURSO_MODULOS_BI FOR CURSO_MODULOS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID_MODULO IS NULL) THEN
    NEW.ID_MODULO = GEN_ID(GEN_CURSO_MODULOS_ID,1);
END
^

SET TERM ; ^

