  MODULE('GENERAR_CUOTAS001.CLW')
FACTURAR_DETALLE2      PROCEDURE                      !GENERA DETALLE FACTURA POR CUOTA
deuda2                 PROCEDURE
FACTURAR_CABECERA2     PROCEDURE                      !GENERA FACTURA POR CUOTA
SelectUSUARIO          PROCEDURE                      !Select a USUARIO Record
UpdateFACTURA          PROCEDURE                      !Actualizacion FACTURA
SelectSOCIOS           PROCEDURE                      !Select a SOCIOS Record
ArchivoFACTURA         PROCEDURE                      !Browse the FACTURA file
calcula_monto          PROCEDURE                      !GENERA DETALLE FACTURA POR CUOTA
  END
