  MODULE('GESTION032.CLW')
SelectPAIS             PROCEDURE                      !Select a PAIS Record
UpdateLOCALIDAD        PROCEDURE                      !Actualizacion LOCALIDAD
BrowseLOCALIDAD        PROCEDURE                      !Browse the LOCALIDAD file
SelectTIPO_INSTITUCION PROCEDURE                      !Select a TIPO_INSTITUCION Record
UpdateINSTITUCION      PROCEDURE                      !Actualizacion INSTITUCION
BrowseINSTITUCION      PROCEDURE                      !Browse the INSTITUCION file
UpdateINSPECTOR        PROCEDURE                      !Actualizacion INSPECTOR
BrowseINSPECTOR        PROCEDURE                      !Browse the INSPECTOR file
UpdateESPECIALIDAD     PROCEDURE                      !Actualizacion ESPECIALIDAD
BrowseESPECIALIDAD     PROCEDURE                      !Browse the ESPECIALIDAD file
  END
