  MODULE('GESTION013.CLW')
IMPRIMIR_COBRO_SEGURO_LIQ PROCEDURE                   !Recibo de Pago 
IMPRIMIR_COBRO_GTO_ADM PROCEDURE                      !Recibo de Pago 
IMPRIMIR_COBRO_CUOTA_LIQ PROCEDURE                    !Recibo de Pago 
Cargar_Recibo          PROCEDURE
SelectSUBCUENTAS       PROCEDURE                      !Select a SUBCUENTAS Record
Pagos_Liquidacion      PROCEDURE                      !Browse the PAGOS_LIQUIDACION File
LIQUIDACION_PAGO_FORM  PROCEDURE                      !Actualizacion LIQUIDACION
LIQUIDACION_PAGO       PROCEDURE                      !Browse the LIQUIDACION File
GENERAR_DISKETTE       PROCEDURE                      !Window
IMPRIMIR_RANKING       PROCEDURE                      !Report the RANKING File
  END
