  MODULE('GESTION030.CLW')
BrowseTIPO_CONVENIO    PROCEDURE                      !Browse the TIPO_CONVENIO file
BrowseSOCIOS           PROCEDURE                      !Browse the SOCIOS file
IMPRIMIR_SOLICITUD_MATRICULACION PROCEDURE
IMPRIMIR_CERTIFICADO_ALTA PROCEDURE
UpdateSERVICIOXSOCIO   PROCEDURE                      !Actualizacion SERVICIOXSOCIO
SelectSERVICIOS        PROCEDURE                      !Select a SERVICIOS Record
BrowseSERVICIOXSOCIO   PROCEDURE                      !Browse the SERVICIOXSOCIO file
UpdateSERVICIOS        PROCEDURE                      !Actualizacion SERVICIOS
BrowseSERVICIOS        PROCEDURE                      !Browse the SERVICIOS file
UpdateRENUNCIA         PROCEDURE                      !Actualizacion RENUNCIA
  END
