  MODULE('GESTION027.CLW')
CUPON_DE_PAGO2         PROCEDURE
FACTURAR_CABECERA_CUPON PROCEDURE
CUPON_DE_PAGO1         PROCEDURE
IMPRIMIR_RECIBO_CANCELACION PROCEDURE
UpdateCONVENIO1        PROCEDURE                      !Actualizacion CONVENIO
CANCELAR_CONVENIO      PROCEDURE                      !Browse the CONVENIO File
IMPRIMIR_PAGO_CONVENIO PROCEDURE                      !Recibo de Pago 
UpdatePAGO_CONVENIO    PROCEDURE                      !Actualizacion PAGO_CONVENIO
SelectCoutaConvenio    PROCEDURE                      !Browse the CONVENIO_DETALLE File
PAGO_CONVENIO          PROCEDURE                      !Browse the PAGO_CONVENIO File
  END
