  MODULE('GESTION022.CLW')
FACTURA_ANUAL_IND      PROCEDURE                      !Browse the INGRESOS_FACTURA file
IMPRIMIR_PAGO_CURSO    PROCEDURE                      !Recibo de Pago 
CURSOS_PAGOS           PROCEDURE                      !Browse the CURSO_INSCRIPCION File
SelectTIPO_PROVEEDOR   PROCEDURE                      !Select a TIPO_PROVEEDOR Record
UpdatePROVEEDORES      PROCEDURE                      !Actualizacion PROVEEDORES
SelectPROVEEDORES      PROCEDURE                      !Select a PROVEEDORES Record
UpdateCURSO_INSCRIPCION PROCEDURE                     !Actualizacion CURSO_INSCRIPCION
SelectCURSO            PROCEDURE                      !Select a CURSO Record
SelectSUBCUENTAS_INGRESOS_SIN_FILTRO PROCEDURE        !Select a SUBCUENTAS Record
CURSOS_INSCRIPCION     PROCEDURE                      !Browse the CURSO_INSCRIPCION File
  END
