  MODULE('GESTION004.CLW')
SelectINSTITUCION      PROCEDURE                      !Select a INSTITUCION Record
SelectMCENTRO_SALUD    PROCEDURE                      !Select a MCENTRO_SALUD Record
SelectCOBERTURA        PROCEDURE                      !Select a COBERTURA Record
SelectCIRCULO          PROCEDURE                      !Select a CIRCULO Record
SelectBANCO            PROCEDURE                      !Select a BANCO Record
VER_SOCIOS             PROCEDURE                      !Browse the SOCIOS file
IMPRIMIR_PADRON_LOCALIDAD_BAJAS PROCEDURE(STRING)
IMPRIMIR_PADRON_LOCALIDAD_TOTAL PROCEDURE(STRING)
ETIQUETAS_TAGS         PROCEDURE
CARNET_TAGS            PROCEDURE
  END
