  MODULE('GESTION015.CLW')
NomencladorXOS         PROCEDURE                      !Browse the NOMENCLADORXOS File
UpdateSOCIOSXOS        PROCEDURE                      !Actualizacion SOCIOSXOS
BrowseSOCIOSXOSBySOC3:FK_SOCIOSXOS_OS PROCEDURE       !Browse the SOCIOSXOS file by SOC3:FK_SOCIOSXOS_OS
IMPRIMIR_MANDATO       PROCEDURE
UpdateOS_PLANES        PROCEDURE                      !Actualizacion OS_PLANES
BrowseOS_PLANESByOS_:FK_OS_PLANES_OS PROCEDURE        !Browse the OS_PLANES file by OS_:FK_OS_PLANES_OS
Formulario_NOMENCLADOR PROCEDURE                      !Actualizacion NOMENCLADOR
Nomenclador            PROCEDURE                      !Browse the NOMENCLADOR File
RECIBO_LIQUIDACION     PROCEDURE                      !Recibo de Pago 
UpdateLIQUIDACION      PROCEDURE                      !Actualizacion LIQUIDACION
  END
