  MODULE('GESTION012.CLW')
CONF_EMP2              PROCEDURE                      !Actualizacion CONF_EMP
CONF_EMP               PROCEDURE                      !Administrador de CONF_EMP
UpdateCIRCULO          PROCEDURE                      !Actualizacion CIRCULO
BrowseCIRCULOS         PROCEDURE                      !Browse the CIRCULO File
SelectOBRA_SOCIAL      PROCEDURE                      !Select a OBRA_SOCIAL Record
LIQUIDACION_PRESENTACION PROCEDURE                    !Window
LIQUIDACION_PRESENTACION_2 PROCEDURE                  !Browse the RANKING File
LIQUIDACION_PRESENTACION_1 PROCEDURE
IMPRIMIR_PAGO_LIQUIDACION PROCEDURE
Formulario_PAGOS_LIQUIDACION PROCEDURE                !Actualizacion PAGOS_LIQUIDACION
  END
