  MODULE('GESTION003.CLW')
IMPRIMIR_CONSULTORIO_CANTIDAD PROCEDURE
IMPRIMIR_CONSULTORIO_SOCIO PROCEDURE                  !Report the CONSULTORIO SOCIO
Reporte:COBERTURA      PROCEDURE                      !Print the COBERTURA File
SelectTIPO_IVA         PROCEDURE                      !Select a TIPO_IVA Record
UpdateSOCIOS           PROCEDURE                      !Actualizacion SOCIOS
SelectTIPO_DOC         PROCEDURE                      !Select a TIPO_DOC Record
SelectZONA_VIVIENDA    PROCEDURE                      !Select a ZONA_VIVIENDA Record
SelectTIPO_TITULO      PROCEDURE                      !Select a TIPO_TITULO Record
SelectMINISTERIO       PROCEDURE                      !Select a MINISTERIO Record
SelectLOCALIDAD        PROCEDURE                      !Select a LOCALIDAD Record
  END
