  MODULE('GESTION010.CLW')
ABM_CUOTA_ANUAL        PROCEDURE                      !Administrador de CONTROL_CUOTA
SelectBANCO_COD_REG    PROCEDURE                      !Select a BANCO_COD_REG Record
UpdateBANCO            PROCEDURE                      !Actualizacion BANCO
ABM_BANCOS             PROCEDURE                      !Browse the BANCO File
UpdateBANCO_COD_REG    PROCEDURE                      !Actualizacion BANCO_COD_REG
ABM_BANCO_COG_REGISTRO PROCEDURE                      !Browse the BANCO_COD_REG File
UpdateTRABAJO          PROCEDURE                      !Actualizacion TRABAJO
Trabajos               PROCEDURE                      !Administrador de TRABAJO
SelectFONDOS           PROCEDURE                      !Select a FONDOS Record
UpdateSUBCUENTAS       PROCEDURE                      !Actualizacion SUBCUENTAS
  END
