  MODULE('GESTION031.CLW')
BrowseRENUNCIA         PROCEDURE                      !Browse the RENUNCIA file
IMPRIMIR_RENUNCIA_DEFINITIVA PROCEDURE
UpdatePAIS             PROCEDURE                      !Actualizacion PAIS
BrowsePAIS             PROCEDURE                      !Browse the PAIS file
UpdatePAGOS            PROCEDURE                      !Actualizacion PAGOS
CARGAR_FACTURA_PAGO    PROCEDURE                      !Carga la factura en el pago 
BrowsePAGOS            PROCEDURE                      !Browse the PAGOS file
UpdatePADRONXESPECIALIDAD PROCEDURE                   !Actualizacion PADRONXESPECIALIDAD
SelectESPECIALIDAD     PROCEDURE                      !Select a ESPECIALIDAD Record
BrowsePADRONXESPECIALIDAD PROCEDURE                   !Browse the PADRONXESPECIALIDAD file
  END
