  MODULE('GESTION021.CLW')
IMPRIMIR_CAJA_CUOTAS   PROCEDURE
IMPRIMIR_CAJA          PROCEDURE
Exportar_Web           PROCEDURE
Exportar_Web_FROM      PROCEDURE
Exportar_Web_2         PROCEDURE
AboutWindow            PROCEDURE                      !The About Window
IMPRIMIR_PAGO_ANUAL    PROCEDURE                      !Recibo de Pago 
GENERAR_FACTURA_ANUAL  PROCEDURE
FACTURA_ANUAL_TOTAL    PROCEDURE                      !Window
UpdateINGRESOS_FACTURA PROCEDURE                      !Form INGRESOS_FACTURA
  END
