  MODULE('GESTION037.CLW')
IMPRIMIR_COMPROBANTE_EGRESO PROCEDURE                 !--FINANZAS --
UpdateEGRESOS          PROCEDURE                      !Actualizacion INGRESOS
SelectTIPO_COMPROBANTE PROCEDURE                      !Select a TIPO_COMPROBANTE Record
ABM_EGRESOS            PROCEDURE                      !Administrador de INGRESOS
ANULAR_GASTOS          PROCEDURE                      !Actualizacion INGRESOS
ABM_PROVEEDOR          PROCEDURE                      !Administrador de PROVEEDORES
Formulario_INFORME     PROCEDURE                      !Actualizacion INFORME
ABM_INFORMES           PROCEDURE                      !Administrador de INFORME
SelectCONSULTORIO1     PROCEDURE                      !Select a CONSULTORIO Record
IMPRIMIR_CERTIFICADO_HABILITACION4 PROCEDURE
  END
