  MODULE('GESTION035.CLW')
imprimir_consultorio_adherente PROCEDURE(STRING, STRING) !Imprime Consultorio con Adherentes
UpdateCOBERTURA        PROCEDURE                      !Actualizacion COBERTURA
BrowseCOBERTURA        PROCEDURE                      !Browse the COBERTURA file
IMPRIMIR_COMPROBANTE_INGRESO PROCEDURE
UpdateINGRESOS         PROCEDURE                      !Actualizacion INGRESOS
SelectSUBCUENTAS_INGRESOS PROCEDURE                   !Select a SUBCUENTAS Record
ABM_INGRESOS           PROCEDURE                      !Administrador de INGRESOS
ANULAR_INGRESOS        PROCEDURE                      !Actualizacion INGRESOS
IMPRIMIR_RECIBOS_EMITIDOS2 PROCEDURE
RECIBOS_EMITIDOS_WINDOWS PROCEDURE
  END
