  MODULE('GESTION008.CLW')
MEDPTOS                PROCEDURE                      !Administrador de MEDPTO
FormaZONA_VIVIENDA     PROCEDURE                      !Actualizacion ZONA_VIVIENDA
BrowseZONA_VIVIENDA    PROCEDURE                      !Catálogo de ZONA_VIVIENDA
FormaUSUARIO           PROCEDURE                      !Actualizacion USUARIO
BrowseUSUARIO          PROCEDURE                      !Catálogo de USUARIO
UpdateTIPO_PROVEEDOR   PROCEDURE                      !Actualizacion TIPO_PROVEEDOR
ABM_TIPO_PROVEEDOR     PROCEDURE                      !Browse the TIPO_PROVEEDOR File
UpdateTIPO_IVA         PROCEDURE                      !Actualizacion TIPO_IVA
ABM_TIPO_IVA           PROCEDURE                      !Browse the TIPO_IVA File
Formulario_TIPO_COMPROBANTE PROCEDURE                 !Actualizacion TIPO_COMPROBANTE
  END
