  MODULE('GESTION006.CLW')
E_MAILS                PROCEDURE                      !Browse the SOCIOS file
SelectTRABAJO          PROCEDURE                      !Select a TRABAJO Record
UpdateSOCIOSXTRABAJO   PROCEDURE                      !Actualizacion SOCIOSXTRABAJO
ABMTRABAJOSXSOCIOS     PROCEDURE                      !Administrador de SOCIOSXTRABAJO
IMPRIMIR_INGRESO_ME    PROCEDURE
Formulario_ME          PROCEDURE                      !Actualizacion ME
SelectMETIPO           PROCEDURE                      !Select a METIPO Record
ME                     PROCEDURE                      !Administrador de ME
SelectMEESTADO         PROCEDURE                      !Select a MEESTADO Record
SelectMEDPTO           PROCEDURE                      !Select a MEDPTO Record
  END
