  MODULE('GESTION009.CLW')
ABM_TIPO_COMPROBANTE   PROCEDURE                      !Administrador de TIPO_COMPROBANTE
FormaTIPO_DOC          PROCEDURE                      !Actualizacion TIPO_DOC
BrowseTIPO_DOC         PROCEDURE                      !Catálogo de TIPO_DOC
UpdateTIPO_COBERTURA   PROCEDURE                      !Actualizacion TIPO_COBERTURA
ABM_TIPOCUOTA          PROCEDURE                      !Browse the TIPO_COBERTURA File
ABM_NIVEL_FORMACION    PROCEDURE                      !Actualizacion NIVEL_FORMACION
SelectNIVEL_FORMACION  PROCEDURE                      !Select a NIVEL_FORMACION Record
UpdateTIPO_TITULO      PROCEDURE                      !Actualizacion TIPO_TITULO
ABM_TITULO             PROCEDURE                      !Administrador de TIPO_TITULO
UpdateCONTROL_CUOTA    PROCEDURE                      !Actualizacion CONTROL_CUOTA
  END
