  MODULE('GESTION011.CLW')
SelectCUENTAS          PROCEDURE                      !Select a CUENTAS Record
ABMSUBCUENTAS          PROCEDURE                      !Administrador de SUBCUENTAS
UpdateFORMA_PAGO       PROCEDURE                      !Actualizacion FORMA_PAGO
ABM_FORMA_PAGO         PROCEDURE                      !Browse the FORMA_PAGO File
UpdateFONDOS           PROCEDURE                      !Actualizacion FONDOS
ABM_FONDOS             PROCEDURE                      !Administrador de FONDOS
UpdateCUENTAS          PROCEDURE                      !Actualizacion CUENTAS
ABMCUENTAS             PROCEDURE                      !Administrador de CUENTAS
UpdateTIPO_EQUIPO      PROCEDURE                      !Actualizacion TIPO_EQUIPO
ABMEEQUIPOS            PROCEDURE                      !Browse the TIPO_EQUIPO File
  END
