  MODULE('GESTION002.CLW')
Reporte:ESPECIALIDAD   PROCEDURE                      !Print the ESPECIALIDAD File
Reporte:CV             PROCEDURE                      !Print the CV File
SelectSOCIOS           PROCEDURE                      !Select a SOCIOS Record
Reporte:CONVENIO       PROCEDURE                      !DEUDA POR SOCIO 
Reporte:CONVENIO_IMPAGO PROCEDURE
Reporte:CONVENIO_TOTAL PROCEDURE
Reporte:CONVENIO_SOCIO_TOTAL PROCEDURE
Reporte:CONVENIO_PAGO  PROCEDURE
IMPRIMIR_CONSULTORIOS  PROCEDURE                      !PADRON POR CIRCULO
Reporte:CONSULTORIO    PROCEDURE                      !Report the CONSULTORIO File
  END
