  MODULE('GESTION001.CLW')
SEGURIDAD              FUNCTION(),BYTE                !SEGURIDAD
Reporte:TIPO_INSTITUCION PROCEDURE                    !Print the TIPO_INSTITUCION File
Reporte:TIPO_CURSO     PROCEDURE                      !Print the TIPO_CURSO File
Reporte:TIPO_CONVENIO  PROCEDURE                      !Print the TIPO_CONVENIO File
Reporte:PAIS           PROCEDURE                      !Print the PAIS File
Reporte:PAGOS          PROCEDURE                      !Print the PAGOS File
Reporte:LOCALIDAD      PROCEDURE                      !Print the LOCALIDAD File
Reporte:INSTITUCION    PROCEDURE                      !Print the INSTITUCION File
Reporte:INSPECTOR      PROCEDURE                      !Print the INSPECTOR File
  END
