  MODULE('GESTION007.CLW')
me_imprimir_diario     PROCEDURE
ME_imprimir_ingreso    PROCEDURE                      !Window
SelectME               PROCEDURE                      !Select a ME Record
Formulario_MS          PROCEDURE                      !Actualizacion MS
MS                     PROCEDURE                      !Administrador de MS
Formulario_METIPO      PROCEDURE                      !Actualizacion METIPO
METIPO                 PROCEDURE                      !Administrador de METIPO
Formulario_MEESTADO    PROCEDURE                      !Actualizacion MEESTADO
MEESTADOS              PROCEDURE                      !Administrador de MEESTADO
Formulario_MEDPTO      PROCEDURE                      !Actualizacion MEDPTO
  END
