  MODULE('GESTION025.CLW')
VER_PAGOS3             PROCEDURE(STRING,STRING)
UpdatePAGOSXCIRCULO    PROCEDURE                      !Actualizacion PAGOSXCIRCULO
ABMPAGOSXCIRCULO       PROCEDURE                      !Browse the PAGOSXCIRCULO File
IMPRIMIR_PAGO          PROCEDURE                      !Recibo de Pago 
UpdatePAGOS1           PROCEDURE                      !Actualizacion PAGOS
SelectSUBCUENTAS_cuotas PROCEDURE                     !Select a SUBCUENTAS Record
PAGOS_AFECTADOS        PROCEDURE                      !Browse the PAGOS file
GENERAR_ARCHIVO_BEBITO PROCEDURE
GENERAR_LIQUIDACION    PROCEDURE                      !Window
VER_FACTURAS           PROCEDURE                      !Browse the FACTURA File
  END
