  MODULE('GESTION033.CLW')
UpdateCV               PROCEDURE                      !Actualizacion CV
BrowseCV               PROCEDURE                      !Browse the CV file
IMPRIMIR_CONVENIO      PROCEDURE
UpdateCONVENIO         PROCEDURE                      !Actualizacion CONVENIO
CANCELAR_CUOTA         PROCEDURE                      !Process the FACTURA File
CALCULAR_CUOTA         PROCEDURE                      !Process the FACTURA File
SelectTIPO_CONVENIO    PROCEDURE                      !Select a TIPO_CONVENIO Record
BrowseCONVENIO         PROCEDURE                      !Browse the CONVENIO File
Cuotas_canceladas      PROCEDURE                      !Administrador de FACTURA_CONVENIO
UpdateCONSULTORIO      PROCEDURE                      !Actualizacion CONSULTORIO
  END
